services:
  db:
    image: mysql:8
    environment:
      MYSQL_ROOT_PASSWORD: senha123
      MYSQL_DATABASE: almoxarifado
    ports:
      - "3307:3306"
    volumes:
      - dbdata:/var/lib/mysql
      - ./Almoxarifado.sql:/docker-entrypoint-initdb.d/Almoxarifado.sql

  api:
    build:
      context: .
      dockerfile: banco/Dockerfile.flask
    ports:
      - "5000:5000"
    depends_on:
      - db

volumes:
  dbdata:
